import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBookOpen,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClipboardList,
  faCopy,
  faEllipsis,
  faFileLines,
  faGear,
  faGripVertical,
  faImage,
  faListCheck,
  faMinus,
  faPen,
  faSun,
  faTags,
  faTrashCan,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBookOpen,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClipboardList,
  faCopy,
  faEllipsis,
  faFileLines,
  faGear,
  faGripVertical,
  faImage,
  faListCheck,
  faMinus,
  faPen,
  faSun,
  faTags,
  faTrashCan,
  faXmark,
)

export const appIcons = {
  'arrow-left': faArrowLeft,
  'arrow-right': faArrowRight,
  'arrow-up': faArrowUp,
  book: faBookOpen,
  'chart-column': faChartColumn,
  check: faCheck,
  'chevron-down': faChevronDown,
  'chevron-left': faChevronLeft,
  'chevron-right': faChevronRight,
  'clipboard-list': faClipboardList,
  copy: faCopy,
  ellipsis: faEllipsis,
  'file-lines': faFileLines,
  gear: faGear,
  'grip-vertical': faGripVertical,
  image: faImage,
  'list-check': faListCheck,
  minus: faMinus,
  pen: faPen,
  sun: faSun,
  tags: faTags,
  trash: faTrashCan,
  xmark: faXmark,
} as const

export type AppIconName = keyof typeof appIcons
