import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBolt,
  faBookOpen,
  faBriefcase,
  faBug,
  faCalendarDays,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClipboardList,
  faCode,
  faComments,
  faCopy,
  faEllipsis,
  faFileLines,
  faFlag,
  faGear,
  faGripVertical,
  faImage,
  faLightbulb,
  faListCheck,
  faMinus,
  faPen,
  faRocket,
  faStar,
  faSun,
  faTags,
  faToolbox,
  faTrashCan,
  faUser,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBolt,
  faBookOpen,
  faBriefcase,
  faBug,
  faCalendarDays,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClipboardList,
  faCode,
  faComments,
  faCopy,
  faEllipsis,
  faFileLines,
  faFlag,
  faGear,
  faGripVertical,
  faImage,
  faLightbulb,
  faListCheck,
  faMinus,
  faPen,
  faRocket,
  faStar,
  faSun,
  faTags,
  faToolbox,
  faTrashCan,
  faUser,
  faUsers,
  faXmark,
);

export const appIcons = {
  "arrow-left": faArrowLeft,
  "arrow-right": faArrowRight,
  "arrow-up": faArrowUp,
  bolt: faBolt,
  book: faBookOpen,
  briefcase: faBriefcase,
  bug: faBug,
  calendar: faCalendarDays,
  "chart-column": faChartColumn,
  check: faCheck,
  "chevron-down": faChevronDown,
  "chevron-left": faChevronLeft,
  "chevron-right": faChevronRight,
  "clipboard-list": faClipboardList,
  code: faCode,
  comments: faComments,
  copy: faCopy,
  ellipsis: faEllipsis,
  "file-lines": faFileLines,
  flag: faFlag,
  gear: faGear,
  "grip-vertical": faGripVertical,
  image: faImage,
  lightbulb: faLightbulb,
  "list-check": faListCheck,
  minus: faMinus,
  pen: faPen,
  rocket: faRocket,
  star: faStar,
  sun: faSun,
  tags: faTags,
  toolbox: faToolbox,
  trash: faTrashCan,
  user: faUser,
  users: faUsers,
  xmark: faXmark,
} as const;

export type AppIconName = keyof typeof appIcons;
